## Local Configuration ##
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
  liquibase:
    enabled: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        temp:
          use_jdbc_metadata_defaults: false

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

springdoc:
  packages-to-scan: com.ing.broker.api
